version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # 只挂载 Flask 需要处理的特殊文件（JSON 等）
      - ./static:/app/static:ro
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=false

  # 可选：添加 Nginx 作为反向代理
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # 以只读方式挂载静态文件
      - ./static:/usr/share/nginx/html/static:ro
    depends_on:
      - web
    restart: unless-stopped
